- name: Install Wireguard
  apt:
    name:
      - wireguard
    state: present

- name: Create server wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: server_wg0.conf.j2
    owner: "{{ vps_username }}"
    group: "{{ vps_username }}"
    mode: "0600"

- name: Enable and persist ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: Start wireguard and enable on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    daemon_reload: true
    state: started
