version: "3.8"
services:
  selenium:
    container_name: "selenium"
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - my-proxy-net
    restart: always

networks:
  my-proxy-net:
    name: my_network
    external: true
