version: "3.1"

volumes:
  psql_volume:

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - psql_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "5432"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    name: my_network
    external: true
