CREATE DATABASE IF NOT EXISTS superbot;
CREATE DATABASE IF NOT EXISTS superchess; 
CREATE DATABASE IF NOT EXISTS supperled; 

GRANT ALL PRIVILEGES ON *.* TO 'USERNAME'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON superbot.* TO 'USERNAME'@'%';
-- GRANT ALL PRIVILEGES ON superchess.* TO 'USERNAME'@'%';
