version: '3.1'
  
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./letsencrypt:/etc/letsencrypt