version: "3.1"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    network_mode: "host"
    environment:
      - SITE_URL=${SITE_URL}
      - CERT_EMAIL=${CERT_EMAIL}
    ports:
      - "80:80"
    volumes:
      - ./files:/home/files
      - ./letsencrypt:/etc/letsencrypt
      - ../../static/chess_frontend:/chess_frontend
      - ../../static/botmanager_frontend:/botmanager_frontend
