version: '3.1'

volumes:
  psql_volume:

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_USER
      POSTGRES_USER: $POSTGRES_PASSWORD
    volumes:
      - psql_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"