- name: Initial configuration of Ubuntu VPS
  hosts: vps
  become: yes

  tasks:
    - name: Load vars locally from secrets.yaml
      ansible.builtin.include_vars:
        file: secrets.yaml
      delegate_to: localhost

    - name: Ensure the correct timezone is configured
      timezone:
        name: Europe/Warsaw

    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create wheel group
      group:
        name: wheel
        state: present

    - name: Make users passwordless for sudo in group wheel
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Creating new user
      user:
        name: "{{ vps_username }}"
        comment: Creating new user
        groups: wheel,docker
        shell: /bin/bash
        create_home: yes

    - name: Upload ssh keys
      authorized_key:
        user: "{{ vps_username }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh_keys/*"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin prohibit-password"

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Creates directory for static files
      file:
        path: "/home/{{ vps_username  }}/static/"
        state: directory
        owner: "{{ vps_username  }}"
        group: "{{ vps_username  }}"

    - name: Creates directories for static files
      file:
        path: "/home/{{ vps_username }}/static/{{ item }}"
        state: directory
        owner: "{{ vps_username }}"
        group: "{{ vps_username }}"
      loop:
        - botmanager_frontend
        - chess_frontend

- name: Install wireguard
  hosts: wireguard
  become: yes
  tasks:
    - include_tasks: install/wireguard_config.yml
# - name: Install prometheus main
#   hosts: prometheus_main
#   become: yes
#   tasks:
#     - include_tasks: install/prometheus_main.yml
