- name: Initial configuration of Ubuntu VPS
  hosts: vps
  become: yes

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create wheel group
      group:
        name: wheel
        state: present

    - name: Make users passwordless for sudo in group wheel
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Creating new user
      user:
        name: "{{ vps_username }}"
        comment: Creating new user
        groups: wheel
        shell: /bin/bash
        create_home: yes

    - name: Upload ssh keys
      authorized_key:
        user: "{{ vps_username }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh_keys/*"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        
    - include_tasks: install/docker.yml