- name: Uploading and restarting containers
  hosts: vps
  become: yes

  tasks:
    - name: Load vars locally from secrets.yaml
      ansible.builtin.include_vars:
        file: secrets.yaml
      delegate_to: localhost

    - name: Creates containers directory
      file:
        path: "/home/{{ vps_username  }}/containers/"
        state: directory
        owner: "{{ vps_username  }}"
        group: "{{ vps_username  }}"

    - name: Copy file with owner and permissions
      synchronize:
        src: ./images/
        dest: /home/{{ vps_username }}/containers/
        rsync_opts:
          - "--chown={{ vps_username  }}:{{ vps_username  }}"
          - "--recursive"
          # - "--delete"

    - name: Restart nginx container
      shell:
        cmd: "docker compose up --build --remove-orphans -d"
        chdir: "/home/{{ vps_username  }}/containers/nginx"
      environment:
        SITE_URL: "{{ site_url }}"
        CERT_EMAIL: "{{ cert_email }}"

    - name: Restart postgres container
      shell:
        cmd: "docker compose up --build --remove-orphans -d"
        chdir: "/home/{{ vps_username  }}/containers/postgres"
      environment:
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"

    - name: Restart rabbitmq container
      shell:
        cmd: "docker compose up --build --remove-orphans -d"
        chdir: "/home/{{ vps_username  }}/containers/rabbitmq"
      environment:
        RABBITMQ_LOGIN: "{{ RABBITMQ_LOGIN }}"
        RABBITMQ_PASSWORD: "{{ RABBITMQ_PASSWORD }}"

    - name: Restart selenium-grid container
      shell:
        cmd: "docker compose up --build --remove-orphans -d"
        chdir: "/home/{{ vps_username  }}/containers/selenium-grid"